package main

import (
	"context"
	"log"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"codex-imagegen-mcp/internal/config"
	"codex-imagegen-mcp/internal/tools"
)

func main() {
	cfg := config.Load()
	d := tools.New(cfg)

	server := mcp.NewServer(&mcp.Implementation{Name: "codex-imagegen-mcp", Version: "0.1.0"}, nil)
	mcp.AddTool(server, &mcp.Tool{
		Name:        "generate_image",
		Description: "Generate a PNG image from a text prompt using Codex's built-in $imagegen skill, saving it to the given 'out' path.",
	}, d.GenerateImage)
	mcp.AddTool(server, &mcp.Tool{
		Name:        "check_codex",
		Description: "Report whether the codex CLI is installed, its version, and whether it is logged in.",
	}, d.CheckCodex)
	mcp.AddTool(server, &mcp.Tool{
		Name:        "list_recent",
		Description: "List images recently generated by this server (path, prompt, dimensions, timestamp).",
	}, d.ListRecent)

	if err := server.Run(context.Background(), &mcp.StdioTransport{}); err != nil {
		log.Fatalf("server exited: %v", err) // log.Fatal writes to stderr — never stdout
	}
}
